-- Add Medium Difficulty Questions Only (Fixed for Supabase JSONB)
-- This will add questions to reach 20 total per category
-- Run this in Supabase SQL Editor

-- SCIENCE - Add medium difficulty questions
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('SCIENCE', 'What is the chemical symbol for gold?', 'mcq', '["Au", "Ag", "Fe", "Cu"]'::jsonb, 0, null),
('SCIENCE', 'Which planet is known as the Red Planet?', 'mcq', '["Venus", "Mars", "Jupiter", "Saturn"]'::jsonb, 1, null),
('SCIENCE', 'What is the speed of light in vacuum?', 'mcq', '["299,792,458 m/s", "199,792,458 m/s", "399,792,458 m/s", "99,792,458 m/s"]'::jsonb, 0, null),
('SCIENCE', 'What is the largest organ in the human body?', 'mcq', '["Heart", "Brain", "Skin", "Liver"]'::jsonb, 2, null),
('SCIENCE', 'Which gas makes up most of Earth''s atmosphere?', 'mcq', '["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"]'::jsonb, 2, null),
('SCIENCE', 'What is the powerhouse of the cell?', 'mcq', '["Nucleus", "Mitochondria", "Ribosome", "Golgi"]'::jsonb, 1, null),
('SCIENCE', 'How many bones are in the adult human body?', 'mcq', '["186", "206", "226", "246"]'::jsonb, 1, null),
('SCIENCE', 'What is the chemical formula for water?', 'mcq', '["H2O", "CO2", "O2", "N2"]'::jsonb, 0, null),
('SCIENCE', 'Which vitamin is produced when skin is exposed to sunlight?', 'mcq', '["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"]'::jsonb, 3, null),
('SCIENCE', 'What is the smallest unit of matter?', 'mcq', '["Molecule", "Atom", "Cell", "Particle"]'::jsonb, 1, null),
('SCIENCE', 'Which force keeps planets in orbit around the sun?', 'mcq', '["Magnetic force", "Gravity", "Friction", "Nuclear force"]'::jsonb, 1, null),
('SCIENCE', 'What is the process by which plants make their own food?', 'mcq', '["Respiration", "Photosynthesis", "Digestion", "Circulation"]'::jsonb, 1, null),
('SCIENCE', 'Which element has the atomic number 1?', 'mcq', '["Helium", "Hydrogen", "Carbon", "Oxygen"]'::jsonb, 1, null),
('SCIENCE', 'What is the hardest natural substance on Earth?', 'mcq', '["Gold", "Iron", "Diamond", "Platinum"]'::jsonb, 2, null),
('SCIENCE', 'Which part of the brain controls balance and coordination?', 'mcq', '["Cerebrum", "Cerebellum", "Brainstem", "Medulla"]'::jsonb, 1, null),
('SCIENCE', 'What is the study of fossils called?', 'mcq', '["Geology", "Archaeology", "Paleontology", "Meteorology"]'::jsonb, 2, null),
('SCIENCE', 'Which blood type is considered the universal donor?', 'mcq', '["A+", "B+", "AB+", "O-"]'::jsonb, 3, null),
('SCIENCE', 'What is the boiling point of water at sea level?', 'mcq', '["90°C", "100°C", "110°C", "120°C"]'::jsonb, 1, null),
('SCIENCE', 'Which planet has the most moons?', 'mcq', '["Earth", "Mars", "Jupiter", "Saturn"]'::jsonb, 2, null),
('SCIENCE', 'What is the medical term for high blood pressure?', 'mcq', '["Hypotension", "Hypertension", "Hyperglycemia", "Hypoglycemia"]'::jsonb, 1, null),

-- GEN MATH - Add medium difficulty questions  
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('GEN MATH', 'What is the value of π (pi) approximately?', 'mcq', '["2.14", "3.14", "4.14", "5.14"]'::jsonb, 1, null),
('GEN MATH', 'What is the square root of 144?', 'mcq', '["10", "11", "12", "13"]'::jsonb, 2, null),
('GEN MATH', 'How many degrees are in a triangle?', 'mcq', '["90", "120", "180", "360"]'::jsonb, 2, null),
('GEN MATH', 'What is 15% of 200?', 'mcq', '["25", "30", "35", "40"]'::jsonb, 1, null),
('GEN MATH', 'What is the next number in the sequence: 2, 4, 8, 16, ?', 'mcq', '["24", "32", "64", "128"]'::jsonb, 1, null),
('GEN MATH', 'What is the area of a circle with radius 5?', 'mcq', '["15π", "20π", "25π", "30π"]'::jsonb, 2, null),
('GEN MATH', 'What is 7² (7 squared)?', 'mcq', '["42", "49", "56", "64"]'::jsonb, 1, null),
('GEN MATH', 'What is the prime factorization of 12?', 'mcq', '["2×2×3", "2×6", "3×4", "12×1"]'::jsonb, 0, null),
('GEN MATH', 'What is the value of x in: 2x + 4 = 12?', 'mcq', '["2", "3", "4", "5"]'::jsonb, 2, null),
('GEN MATH', 'What is the perimeter of a square with side length 6?', 'mcq', '["12", "18", "24", "36"]'::jsonb, 2, null),
('GEN MATH', 'What is 3/4 as a decimal?', 'mcq', '["0.25", "0.5", "0.75", "0.8"]'::jsonb, 2, null),
('GEN MATH', 'What is the least common multiple of 6 and 8?', 'mcq', '["12", "24", "36", "48"]'::jsonb, 1, null),
('GEN MATH', 'What is the volume of a cube with side length 3?', 'mcq', '["9", "18", "27", "36"]'::jsonb, 2, null),
('GEN MATH', 'What is the median of: 3, 7, 2, 9, 5?', 'mcq', '["3", "5", "7", "9"]'::jsonb, 1, null),
('GEN MATH', 'What is 2³ (2 cubed)?', 'mcq', '["4", "6", "8", "16"]'::jsonb, 2, null),
('GEN MATH', 'What is the probability of rolling a 6 on a standard die?', 'mcq', '["1/4", "1/5", "1/6", "1/7"]'::jsonb, 2, null),
('GEN MATH', 'What is the sum of angles in a quadrilateral?', 'mcq', '["180°", "270°", "360°", "450°"]'::jsonb, 2, null),
('GEN MATH', 'What is the value of 5! (5 factorial)?', 'mcq', '["60", "80", "100", "120"]'::jsonb, 3, null),
('GEN MATH', 'What is the greatest common divisor of 24 and 36?', 'mcq', '["6", "8", "12", "18"]'::jsonb, 2, null),
('GEN MATH', 'What is the next prime number after 17?', 'mcq', '["18", "19", "20", "21"]'::jsonb, 1, null),

-- TECHNOLOGY - Add medium difficulty questions
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('TECHNOLOGY', 'What does "HTTP" stand for?', 'mcq', '["HyperText Transfer Protocol", "High Tech Transfer Protocol", "Home Tool Transfer Protocol", "HyperText Technical Protocol"]'::jsonb, 0, null),
('TECHNOLOGY', 'Who founded Microsoft?', 'mcq', '["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"]'::jsonb, 1, null),
('TECHNOLOGY', 'What does "AI" stand for?', 'mcq', '["Automated Intelligence", "Artificial Intelligence", "Advanced Intelligence", "Analytic Intelligence"]'::jsonb, 1, null),
('TECHNOLOGY', 'Which programming language is known as the "language of the web"?', 'mcq', '["Python", "Java", "JavaScript", "C++"]'::jsonb, 2, null),
('TECHNOLOGY', 'What does "URL" stand for?', 'mcq', '["Universal Resource Locator", "Uniform Resource Locator", "Unified Resource Locator", "Universal Reference Locator"]'::jsonb, 1, null),
('TECHNOLOGY', 'Who founded Apple?', 'mcq', '["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"]'::jsonb, 1, null),
('TECHNOLOGY', 'What does "CPU" stand for?', 'mcq', '["Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Computer Program Unit"]'::jsonb, 0, null),
('TECHNOLOGY', 'Which company created Android?', 'mcq', '["Apple", "Microsoft", "Google", "Samsung"]'::jsonb, 2, null),
('TECHNOLOGY', 'What does "RAM" stand for?', 'mcq', '["Read Access Memory", "Random Access Memory", "Run Access Memory", "Read Application Memory"]'::jsonb, 1, null),
('TECHNOLOGY', 'Who founded Facebook?', 'mcq', '["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Larry Page"]'::jsonb, 2, null),
('TECHNOLOGY', 'What does "HTML" stand for?', 'mcq', '["HyperText Markup Language", "High Tech Markup Language", "Home Tool Markup Language", "HyperText Technical Language"]'::jsonb, 0, null),
('TECHNOLOGY', 'Which company created the iPhone?', 'mcq', '["Samsung", "Google", "Apple", "Microsoft"]'::jsonb, 2, null),
('TECHNOLOGY', 'What does "Wi-Fi" stand for?', 'mcq', '["Wireless Fidelity", "Wireless Finder", "Wireless Facility", "Wireless Function"]'::jsonb, 0, null),
('TECHNOLOGY', 'Who founded Google?', 'mcq', '["Steve Jobs", "Bill Gates", "Larry Page", "Mark Zuckerberg"]'::jsonb, 2, null),
('TECHNOLOGY', 'What does "USB" stand for?', 'mcq', '["Universal Serial Bus", "Universal System Bus", "Unified Serial Bus", "Universal Service Bus"]'::jsonb, 0, null),
('TECHNOLOGY', 'Which programming language is primarily used for Android development?', 'mcq', '["Swift", "Kotlin", "Python", "JavaScript"]'::jsonb, 1, null),
('TECHNOLOGY', 'What does "VPN" stand for?', 'mcq', '["Virtual Private Network", "Virtual Public Network", "Visual Private Network", "Virtual Protected Network"]'::jsonb, 0, null),
('TECHNOLOGY', 'Who founded Amazon?', 'mcq', '["Bill Gates", "Steve Jobs", "Jeff Bezos", "Larry Page"]'::jsonb, 2, null),
('TECHNOLOGY', 'What does "API" stand for?', 'mcq', '["Application Programming Interface", "Advanced Programming Interface", "Application Process Interface", "Advanced Process Interface"]'::jsonb, 0, null),
('TECHNOLOGY', 'Which company created Windows?', 'mcq', '["Apple", "Google", "Microsoft", "IBM"]'::jsonb, 2, null),

-- HISTORY - Add medium difficulty questions
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('HISTORY', 'In which year did World War II end?', 'mcq', '["1943", "1944", "1945", "1946"]'::jsonb, 2, null),
('HISTORY', 'Who was the first President of the United States?', 'mcq', '["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"]'::jsonb, 1, null),
('HISTORY', 'Which ancient wonder of the world still stands today?', 'mcq', '["Colossus of Rhodes", "Hanging Gardens", "Great Pyramid of Giza", "Lighthouse of Alexandria"]'::jsonb, 2, null),
('HISTORY', 'In which year did Christopher Columbus reach the Americas?', 'mcq', '["1490", "1491", "1492", "1493"]'::jsonb, 2, null),
('HISTORY', 'Who wrote the Declaration of Independence?', 'mcq', '["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"]'::jsonb, 1, null),
('HISTORY', 'Which empire was known as "the empire on which the sun never sets"?', 'mcq', '["Roman Empire", "British Empire", "Ottoman Empire", "Mongol Empire"]'::jsonb, 1, null),
('HISTORY', 'In which year did the Titanic sink?', 'mcq', '["1910", "1911", "1912", "1913"]'::jsonb, 2, null),
('HISTORY', 'Who was known as the "Iron Lady"?', 'mcq', '["Queen Elizabeth II", "Margaret Thatcher", "Angela Merkel", "Indira Gandhi"]'::jsonb, 1, null),
('HISTORY', 'Which war was fought between the North and South in America?', 'mcq', '["Revolutionary War", "Civil War", "World War I", "World War II"]'::jsonb, 1, null),
('HISTORY', 'In which year did the Berlin Wall fall?', 'mcq', '["1987", "1988", "1989", "1990"]'::jsonb, 2, null),
('HISTORY', 'Who discovered penicillin?', 'mcq', '["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Robert Koch"]'::jsonb, 1, null),
('HISTORY', 'Which ancient civilization built Machu Picchu?', 'mcq', '["Maya", "Aztec", "Inca", "Olmec"]'::jsonb, 2, null),
('HISTORY', 'In which year did the French Revolution begin?', 'mcq', '["1787", "1788", "1789", "1790"]'::jsonb, 2, null),
('HISTORY', 'Who was the first person to walk on the moon?', 'mcq', '["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"]'::jsonb, 1, null),
('HISTORY', 'Which dynasty built the Great Wall of China?', 'mcq', '["Han Dynasty", "Tang Dynasty", "Ming Dynasty", "Qing Dynasty"]'::jsonb, 2, null),
('HISTORY', 'In which year did World War I begin?', 'mcq', '["1912", "1913", "1914", "1915"]'::jsonb, 2, null),
('HISTORY', 'Who painted the Mona Lisa?', 'mcq', '["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"]'::jsonb, 1, null),
('HISTORY', 'Which empire was ruled by Julius Caesar?', 'mcq', '["Greek Empire", "Roman Empire", "Egyptian Empire", "Persian Empire"]'::jsonb, 1, null),
('HISTORY', 'In which year did the American Civil War end?', 'mcq', '["1863", "1864", "1865", "1866"]'::jsonb, 2, null),
('HISTORY', 'Who was the last pharaoh of Egypt?', 'mcq', '["Tutankhamun", "Cleopatra", "Nefertiti", "Hatshepsut"]'::jsonb, 1, null);
