-- Additional Medium Difficulty Questions for Each Category
-- 20 questions per category

-- SCIENCE Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('SCIENCE', 'What is the chemical symbol for gold?', 'mcq', '{"Au", "Ag", "Fe", "Cu"}', 0, null),
('SCIENCE', 'Which planet is known as the Red Planet?', 'mcq', '{"Venus", "Mars", "Jupiter", "Saturn"}', 1, null),
('SCIENCE', 'What is the speed of light in vacuum?', 'mcq', '{"299,792,458 m/s", "199,792,458 m/s", "399,792,458 m/s", "99,792,458 m/s"}', 0, null),
('SCIENCE', 'What is the largest organ in the human body?', 'mcq', '{"Heart", "Brain", "Skin", "Liver"}', 2, null),
('SCIENCE', 'Which gas makes up most of Earth''s atmosphere?', 'mcq', '{"Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"}', 2, null),
('SCIENCE', 'What is the powerhouse of the cell?', 'mcq', '{"Nucleus", "Mitochondria", "Ribosome", "Golgi"}', 1, null),
('SCIENCE', 'How many bones are in the adult human body?', 'mcq', '{"186", "206", "226", "246"}', 1, null),
('SCIENCE', 'What is the chemical formula for water?', 'mcq', '{"H2O", "CO2", "O2", "N2"}', 0, null),
('SCIENCE', 'Which vitamin is produced when skin is exposed to sunlight?', 'mcq', '{"Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"}', 3, null),
('SCIENCE', 'What is the smallest unit of matter?', 'mcq', '{"Molecule", "Atom", "Cell", "Particle"}', 1, null),
('SCIENCE', 'Which force keeps planets in orbit around the sun?', 'mcq', '{"Magnetic force", "Gravity", "Friction", "Nuclear force"}', 1, null),
('SCIENCE', 'What is the process by which plants make their own food?', 'mcq', '{"Respiration", "Photosynthesis", "Digestion", "Circulation"}', 1, null),
('SCIENCE', 'Which element has the atomic number 1?', 'mcq', '{"Helium", "Hydrogen", "Carbon", "Oxygen"}', 1, null),
('SCIENCE', 'What is the hardest natural substance on Earth?', 'mcq', '{"Gold", "Iron", "Diamond", "Platinum"}', 2, null),
('SCIENCE', 'Which part of the brain controls balance and coordination?', 'mcq', '{"Cerebrum", "Cerebellum", "Brainstem", "Medulla"}', 1, null),
('SCIENCE', 'What is the study of fossils called?', 'mcq', '{"Geology", "Archaeology", "Paleontology", "Meteorology"}', 2, null),
('SCIENCE', 'Which blood type is considered the universal donor?', 'mcq', '{"A+", "B+", "AB+", "O-"}', 3, null),
('SCIENCE', 'What is the boiling point of water at sea level?', 'mcq', '{"90°C", "100°C", "110°C", "120°C"}', 1, null),
('SCIENCE', 'Which planet has the most moons?', 'mcq', '{"Earth", "Mars", "Jupiter", "Saturn"}', 2, null),
('SCIENCE', 'What is the medical term for high blood pressure?', 'mcq', '{"Hypotension", "Hypertension", "Hyperglycemia", "Hypoglycemia"}', 1, null),

-- MATHEMATICS Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('MATHEMATICS', 'What is the value of π (pi) approximately?', 'mcq', '{"2.14", "3.14", "4.14", "5.14"}', 1, null),
('MATHEMATICS', 'What is the square root of 144?', 'mcq', '{"10", "11", "12", "13"}', 2, null),
('MATHEMATICS', 'How many degrees are in a triangle?', 'mcq', '{"90", "120", "180", "360"}', 2, null),
('MATHEMATICS', 'What is 15% of 200?', 'mcq', '{"25", "30", "35", "40"}', 1, null),
('MATHEMATICS', 'What is the next number in the sequence: 2, 4, 8, 16, ?', 'mcq', '{"24", "32", "64", "128"}', 1, null),
('MATHEMATICS', 'What is the area of a circle with radius 5?', 'mcq', '{"15π", "20π", "25π", "30π"}', 2, null),
('MATHEMATICS', 'What is 7² (7 squared)?', 'mcq', '{"42", "49", "56", "64"}', 1, null),
('MATHEMATICS', 'What is the prime factorization of 12?', 'mcq', '{"2×2×3", "2×6", "3×4", "12×1"}', 0, null),
('MATHEMATICS', 'What is the value of x in: 2x + 4 = 12?', 'mcq', '{"2", "3", "4", "5"}', 2, null),
('MATHEMATICS', 'What is the perimeter of a square with side length 6?', 'mcq', '{"12", "18", "24", "36"}', 2, null),
('MATHEMATICS', 'What is 3/4 as a decimal?', 'mcq', '{"0.25", "0.5", "0.75", "0.8"}', 2, null),
('MATHEMATICS', 'What is the least common multiple of 6 and 8?', 'mcq', '{"12", "24", "36", "48"}', 1, null),
('MATHEMATICS', 'What is the volume of a cube with side length 3?', 'mcq', '{"9", "18", "27", "36"}', 2, null),
('MATHEMATICS', 'What is the median of: 3, 7, 2, 9, 5?', 'mcq', '{"3", "5", "7", "9"}', 1, null),
('MATHEMATICS', 'What is 2³ (2 cubed)?', 'mcq', '{"4", "6", "8", "16"}', 2, null),
('MATHEMATICS', 'What is the probability of rolling a 6 on a standard die?', 'mcq', '{"1/4", "1/5", "1/6", "1/7"}', 2, null),
('MATHEMATICS', 'What is the sum of angles in a quadrilateral?', 'mcq', '{"180°", "270°", "360°", "450°"}', 2, null),
('MATHEMATICS', 'What is the value of 5! (5 factorial)?', 'mcq', '{"60", "80", "100", "120"}', 3, null),
('MATHEMATICS', 'What is the greatest common divisor of 24 and 36?', 'mcq', '{"6", "8", "12", "18"}', 2, null),
('MATHEMATICS', 'What is the next prime number after 17?', 'mcq', '{"18", "19", "20", "21"}', 1, null),

-- HISTORY Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('HISTORY', 'In which year did World War II end?', 'mcq', '{"1943", "1944", "1945", "1946"}', 2, null),
('HISTORY', 'Who was the first President of the United States?', 'mcq', '{"Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"}', 1, null),
('HISTORY', 'Which ancient wonder of the world still stands today?', 'mcq', '{"Colossus of Rhodes", "Hanging Gardens", "Great Pyramid of Giza", "Lighthouse of Alexandria"}', 2, null),
('HISTORY', 'In which year did Christopher Columbus reach the Americas?', 'mcq', '{"1490", "1491", "1492", "1493"}', 2, null),
('HISTORY', 'Who wrote the Declaration of Independence?', 'mcq', '{"George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"}', 1, null),
('HISTORY', 'Which empire was known as "the empire on which the sun never sets"?', 'mcq', '{"Roman Empire", "British Empire", "Ottoman Empire", "Mongol Empire"}', 1, null),
('HISTORY', 'In which year did the Titanic sink?', 'mcq', '{"1910", "1911", "1912", "1913"}', 2, null),
('HISTORY', 'Who was known as the "Iron Lady"?', 'mcq', '{"Queen Elizabeth II", "Margaret Thatcher", "Angela Merkel", "Indira Gandhi"}', 1, null),
('HISTORY', 'Which war was fought between the North and South in America?', 'mcq', '{"Revolutionary War", "Civil War", "World War I", "World War II"}', 1, null),
('HISTORY', 'In which year did the Berlin Wall fall?', 'mcq', '{"1987", "1988", "1989", "1990"}', 2, null),
('HISTORY', 'Who discovered penicillin?', 'mcq', '{"Marie Curie", "Alexander Fleming", "Louis Pasteur", "Robert Koch"}', 1, null),
('HISTORY', 'Which ancient civilization built Machu Picchu?', 'mcq', '{"Maya", "Aztec", "Inca", "Olmec"}', 2, null),
('HISTORY', 'In which year did the French Revolution begin?', 'mcq', '{"1787", "1788", "1789", "1790"}', 2, null),
('HISTORY', 'Who was the first person to walk on the moon?', 'mcq', '{"Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"}', 1, null),
('HISTORY', 'Which dynasty built the Great Wall of China?', 'mcq', '{"Han Dynasty", "Tang Dynasty", "Ming Dynasty", "Qing Dynasty"}', 2, null),
('HISTORY', 'In which year did World War I begin?', 'mcq', '{"1912", "1913", "1914", "1915"}', 2, null),
('HISTORY', 'Who painted the Mona Lisa?', 'mcq', '{"Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"}', 1, null),
('HISTORY', 'Which empire was ruled by Julius Caesar?', 'mcq', '{"Greek Empire", "Roman Empire", "Egyptian Empire", "Persian Empire"}', 1, null),
('HISTORY', 'In which year did the American Civil War end?', 'mcq', '{"1863", "1864", "1865", "1866"}', 2, null),
('HISTORY', 'Who was the last pharaoh of Egypt?', 'mcq', '{"Tutankhamun", "Cleopatra", "Nefertiti", "Hatshepsut"}', 1, null),

-- GEOGRAPHY Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('GEOGRAPHY', 'What is the capital of France?', 'mcq', '{"London", "Berlin", "Paris", "Madrid"}', 2, null),
('GEOGRAPHY', 'Which is the largest ocean on Earth?', 'mcq', '{"Atlantic", "Indian", "Arctic", "Pacific"}', 3, null),
('GEOGRAPHY', 'What is the longest river in the world?', 'mcq', '{"Amazon", "Nile", "Mississippi", "Yangtze"}', 1, null),
('GEOGRAPHY', 'Which country has the largest population?', 'mcq', '{"India", "China", "USA", "Indonesia"}', 1, null),
('GEOGRAPHY', 'What is the smallest continent?', 'mcq', '{"Europe", "Australia", "Antarctica", "South America"}', 1, null),
('GEOGRAPHY', 'Which desert is the largest in the world?', 'mcq', '{"Sahara", "Arabian", "Gobi", "Antarctica"}', 3, null),
('GEOGRAPHY', 'What is the capital of Japan?', 'mcq', '{"Seoul", "Beijing", "Tokyo", "Bangkok"}', 2, null),
('GEOGRAPHY', 'Which mountain range contains Mount Everest?', 'mcq', '{"Alps", "Rockies", "Andes", "Himalayas"}', 3, null),
('GEOGRAPHY', 'What is the deepest point in Earth''s oceans?', 'mcq', '{"Java Trench", "Mariana Trench", "Puerto Rico Trench", "Tonga Trench"}', 1, null),
('GEOGRAPHY', 'Which country is known as the "Land of the Rising Sun"?', 'mcq', '{"China", "Korea", "Japan", "Thailand"}', 2, null),
('GEOGRAPHY', 'What is the capital of Australia?', 'mcq', '{"Sydney", "Melbourne", "Canberra", "Brisbane"}', 2, null),
('GEOGRAPHY', 'Which river flows through London?', 'mcq', '{"Seine", "Thames", "Danube", "Rhine"}', 1, null),
('GEOGRAPHY', 'What is the largest lake in the world?', 'mcq', '{"Lake Superior", "Lake Victoria", "Caspian Sea", "Lake Baikal"}', 2, null),
('GEOGRAPHY', 'Which country has the most time zones?', 'mcq', '{"Russia", "USA", "China", "France"}', 0, null),
('GEOGRAPHY', 'What is the capital of Brazil?', 'mcq', '{"Rio de Janeiro", "São Paulo", "Brasília", "Salvador"}', 2, null),
('GEOGRAPHY', 'Which is the hottest continent on Earth?', 'mcq', '{"Africa", "South America", "Australia", "Asia"}', 0, null),
('GEOGRAPHY', 'What is the capital of Canada?', 'mcq', '{"Toronto", "Montreal", "Vancouver", "Ottawa"}', 3, null),
('GEOGRAPHY', 'Which country is known as the "Pearl of Africa"?', 'mcq', '{"Kenya", "Tanzania", "Uganda", "Rwanda"}', 2, null),
('GEOGRAPHY', 'What is the largest island in the world?', 'mcq', '{"Madagascar", "Borneo", "Greenland", "New Guinea"}', 2, null),
('GEOGRAPHY', 'Which capital city is known as the "Eternal City"?', 'mcq', '{"Athens", "Rome", "Cairo", "Jerusalem"}', 1, null),

-- SPORTS Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('SPORTS', 'How many players are on a basketball team on the court?', 'mcq', '{"4", "5", "6", "7"}', 1, null),
('SPORTS', 'In which sport would you perform a slam dunk?', 'mcq', '{"Volleyball", "Tennis", "Basketball", "Baseball"}', 2, null),
('SPORTS', 'How many minutes is a professional soccer match?', 'mcq', '{"60", "75", "90", "105"}', 2, null),
('SPORTS', 'In which sport would you find a "hole in one"?', 'mcq', '{"Tennis", "Golf", "Baseball", "Bowling"}', 1, null),
('SPORTS', 'How many rings are on the Olympic flag?', 'mcq', '{"3", "4", "5", "6"}', 2, null),
('SPORTS', 'In which sport would you perform a "slam dunk"?', 'mcq', '{"Volleyball", "Basketball", "Tennis", "Baseball"}', 1, null),
('SPORTS', 'What is the maximum score in ten-pin bowling?', 'mcq', '{"200", "250", "300", "350"}', 2, null),
('SPORTS', 'In which sport would you find a "hat trick"?', 'mcq', '{"Basketball", "Tennis", "Soccer", "Golf"}', 2, null),
('SPORTS', 'How many players are on a volleyball team?', 'mcq', '{"4", "5", "6", "7"}', 2, null),
('SPORTS', 'In which sport would you perform a "home run"?', 'mcq', '{"Cricket", "Baseball", "Softball", "Rounders"}', 1, null),
('SPORTS', 'What is the distance of a marathon?', 'mcq', '{"26.2 km", "32.2 km", "42.2 km", "52.2 km"}', 2, null),
('SPORTS', 'In which sport would you find a "knockout"?', 'mcq', '{"Wrestling", "Boxing", "MMA", "Karate"}', 1, null),
('SPORTS', 'How many periods are in a professional hockey game?', 'mcq', '{"2", "3", "4", "5"}', 1, null),
('SPORTS', 'In which sport would you perform a "serve"?', 'mcq', '{"Basketball", "Tennis", "Baseball", "Golf"}', 1, null),
('SPORTS', 'What is the perfect score in gymnastics?', 'mcq', '{"8.0", "9.0", "10.0", "11.0"}', 2, null),
('SPORTS', 'In which sport would you find a "bullseye"?', 'mcq', '{"Basketball", "Archery", "Darts", "Shooting"}', 2, null),
('SPORTS', 'How many players are on a cricket team?', 'mcq', '{"9", "10", "11", "12"}', 2, null),
('SPORTS', 'In which sport would you perform a "spike"?', 'mcq', '{"Tennis", "Volleyball", "Badminton", "Squash"}', 1, null),
('SPORTS', 'What is the term for three strikes in baseball?', 'mcq', '{"Grand slam", "Hat trick", "Triple play", "Strikeout"}', 1, null),
('SPORTS', 'In which sport would you find a "penalty kick"?', 'mcq', '{"Rugby", "Soccer", "American Football", "Basketball"}', 1, null);
