-- Additional Medium Difficulty Questions for Each Category
-- 20 questions per category - FIXED FOR ACTUAL CATEGORIES

-- SCIENCE Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('SCIENCE', 'What is the chemical symbol for gold?', 'mcq', '{"Au", "Ag", "Fe", "Cu"}', 0, null),
('SCIENCE', 'Which planet is known as the Red Planet?', 'mcq', '{"Venus", "Mars", "Jupiter", "Saturn"}', 1, null),
('SCIENCE', 'What is the speed of light in vacuum?', 'mcq', '{"299,792,458 m/s", "199,792,458 m/s", "399,792,458 m/s", "99,792,458 m/s"}', 0, null),
('SCIENCE', 'What is the largest organ in the human body?', 'mcq', '{"Heart", "Brain", "Skin", "Liver"}', 2, null),
('SCIENCE', 'Which gas makes up most of Earth''s atmosphere?', 'mcq', '{"Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"}', 2, null),
('SCIENCE', 'What is the powerhouse of the cell?', 'mcq', '{"Nucleus", "Mitochondria", "Ribosome", "Golgi"}', 1, null),
('SCIENCE', 'How many bones are in the adult human body?', 'mcq', '{"186", "206", "226", "246"}', 1, null),
('SCIENCE', 'What is the chemical formula for water?', 'mcq', '{"H2O", "CO2", "O2", "N2"}', 0, null),
('SCIENCE', 'Which vitamin is produced when skin is exposed to sunlight?', 'mcq', '{"Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"}', 3, null),
('SCIENCE', 'What is the smallest unit of matter?', 'mcq', '{"Molecule", "Atom", "Cell", "Particle"}', 1, null),
('SCIENCE', 'Which force keeps planets in orbit around the sun?', 'mcq', '{"Magnetic force", "Gravity", "Friction", "Nuclear force"}', 1, null),
('SCIENCE', 'What is the process by which plants make their own food?', 'mcq', '{"Respiration", "Photosynthesis", "Digestion", "Circulation"}', 1, null),
('SCIENCE', 'Which element has the atomic number 1?', 'mcq', '{"Helium", "Hydrogen", "Carbon", "Oxygen"}', 1, null),
('SCIENCE', 'What is the hardest natural substance on Earth?', 'mcq', '{"Gold", "Iron", "Diamond", "Platinum"}', 2, null),
('SCIENCE', 'Which part of the brain controls balance and coordination?', 'mcq', '{"Cerebrum", "Cerebellum", "Brainstem", "Medulla"}', 1, null),
('SCIENCE', 'What is the study of fossils called?', 'mcq', '{"Geology", "Archaeology", "Paleontology", "Meteorology"}', 2, null),
('SCIENCE', 'Which blood type is considered the universal donor?', 'mcq', '{"A+", "B+", "AB+", "O-"}', 3, null),
('SCIENCE', 'What is the boiling point of water at sea level?', 'mcq', '{"90°C", "100°C", "110°C", "120°C"}', 1, null),
('SCIENCE', 'Which planet has the most moons?', 'mcq', '{"Earth", "Mars", "Jupiter", "Saturn"}', 2, null),
('SCIENCE', 'What is the medical term for high blood pressure?', 'mcq', '{"Hypotension", "Hypertension", "Hyperglycemia", "Hypoglycemia"}', 1, null),

-- GEN MATH Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('GEN MATH', 'What is the value of π (pi) approximately?', 'mcq', '{"2.14", "3.14", "4.14", "5.14"}', 1, null),
('GEN MATH', 'What is the square root of 144?', 'mcq', '{"10", "11", "12", "13"}', 2, null),
('GEN MATH', 'How many degrees are in a triangle?', 'mcq', '{"90", "120", "180", "360"}', 2, null),
('GEN MATH', 'What is 15% of 200?', 'mcq', '{"25", "30", "35", "40"}', 1, null),
('GEN MATH', 'What is the next number in the sequence: 2, 4, 8, 16, ?', 'mcq', '{"24", "32", "64", "128"}', 1, null),
('GEN MATH', 'What is the area of a circle with radius 5?', 'mcq', '{"15π", "20π", "25π", "30π"}', 2, null),
('GEN MATH', 'What is 7² (7 squared)?', 'mcq', '{"42", "49", "56", "64"}', 1, null),
('GEN MATH', 'What is the prime factorization of 12?', 'mcq', '{"2×2×3", "2×6", "3×4", "12×1"}', 0, null),
('GEN MATH', 'What is the value of x in: 2x + 4 = 12?', 'mcq', '{"2", "3", "4", "5"}', 2, null),
('GEN MATH', 'What is the perimeter of a square with side length 6?', 'mcq', '{"12", "18", "24", "36"}', 2, null),
('GEN MATH', 'What is 3/4 as a decimal?', 'mcq', '{"0.25", "0.5", "0.75", "0.8"}', 2, null),
('GEN MATH', 'What is the least common multiple of 6 and 8?', 'mcq', '{"12", "24", "36", "48"}', 1, null),
('GEN MATH', 'What is the volume of a cube with side length 3?', 'mcq', '{"9", "18", "27", "36"}', 2, null),
('GEN MATH', 'What is the median of: 3, 7, 2, 9, 5?', 'mcq', '{"3", "5", "7", "9"}', 1, null),
('GEN MATH', 'What is 2³ (2 cubed)?', 'mcq', '{"4", "6", "8", "16"}', 2, null),
('GEN MATH', 'What is the probability of rolling a 6 on a standard die?', 'mcq', '{"1/4", "1/5", "1/6", "1/7"}', 2, null),
('GEN MATH', 'What is the sum of angles in a quadrilateral?', 'mcq', '{"180°", "270°", "360°", "450°"}', 2, null),
('GEN MATH', 'What is the value of 5! (5 factorial)?', 'mcq', '{"60", "80", "100", "120"}', 3, null),
('GEN MATH', 'What is the greatest common divisor of 24 and 36?', 'mcq', '{"6", "8", "12", "18"}', 2, null),
('GEN MATH', 'What is the next prime number after 17?', 'mcq', '{"18", "19", "20", "21"}', 1, null),

-- TECHNOLOGY Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('TECHNOLOGY', 'What does "HTTP" stand for?', 'mcq', '{"HyperText Transfer Protocol", "High Tech Transfer Protocol", "Home Tool Transfer Protocol", "HyperText Technical Protocol"}', 0, null),
('TECHNOLOGY', 'Who founded Microsoft?', 'mcq', '{"Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"}', 1, null),
('TECHNOLOGY', 'What does "AI" stand for?', 'mcq', '{"Automated Intelligence", "Artificial Intelligence", "Advanced Intelligence", "Analytic Intelligence"}', 1, null),
('TECHNOLOGY', 'Which programming language is known as the "language of the web"?', 'mcq', '{"Python", "Java", "JavaScript", "C++"}', 2, null),
('TECHNOLOGY', 'What does "URL" stand for?', 'mcq', '{"Universal Resource Locator", "Uniform Resource Locator", "Unified Resource Locator", "Universal Reference Locator"}', 1, null),
('TECHNOLOGY', 'Who founded Apple?', 'mcq', '{"Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"}', 1, null),
('TECHNOLOGY', 'What does "CPU" stand for?', 'mcq', '{"Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Computer Program Unit"}', 0, null),
('TECHNOLOGY', 'Which company created Android?', 'mcq', '{"Apple", "Microsoft", "Google", "Samsung"}', 2, null),
('TECHNOLOGY', 'What does "RAM" stand for?', 'mcq', '{"Read Access Memory", "Random Access Memory", "Run Access Memory", "Read Application Memory"}', 1, null),
('TECHNOLOGY', 'Who founded Facebook?', 'mcq', '{"Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Larry Page"}', 2, null),
('TECHNOLOGY', 'What does "HTML" stand for?', 'mcq', '{"HyperText Markup Language", "High Tech Markup Language", "Home Tool Markup Language", "HyperText Technical Language"}', 0, null),
('TECHNOLOGY', 'Which company created the iPhone?', 'mcq', '{"Samsung", "Google", "Apple", "Microsoft"}', 2, null),
('TECHNOLOGY', 'What does "Wi-Fi" stand for?', 'mcq', '{"Wireless Fidelity", "Wireless Finder", "Wireless Facility", "Wireless Function"}', 0, null),
('TECHNOLOGY', 'Who founded Google?', 'mcq', '{"Steve Jobs", "Bill Gates", "Larry Page", "Mark Zuckerberg"}', 2, null),
('TECHNOLOGY', 'What does "USB" stand for?', 'mcq', '{"Universal Serial Bus", "Universal System Bus", "Unified Serial Bus", "Universal Service Bus"}', 0, null),
('TECHNOLOGY', 'Which programming language is primarily used for Android development?', 'mcq', '{"Swift", "Kotlin", "Python", "JavaScript"}', 1, null),
('TECHNOLOGY', 'What does "VPN" stand for?', 'mcq', '{"Virtual Private Network", "Virtual Public Network", "Visual Private Network", "Virtual Protected Network"}', 0, null),
('TECHNOLOGY', 'Who founded Amazon?', 'mcq', '{"Bill Gates", "Steve Jobs", "Jeff Bezos", "Larry Page"}', 2, null),
('TECHNOLOGY', 'What does "API" stand for?', 'mcq', '{"Application Programming Interface", "Advanced Programming Interface", "Application Process Interface", "Advanced Process Interface"}', 0, null),
('TECHNOLOGY', 'Which company created Windows?', 'mcq', '{"Apple", "Google", "Microsoft", "IBM"}', 2, null),

-- HISTORY Questions (Medium Difficulty)
INSERT INTO questions (category, question_text, type, options, correct_idx, answer_text) VALUES
('HISTORY', 'In which year did World War II end?', 'mcq', '{"1943", "1944", "1945", "1946"}', 2, null),
('HISTORY', 'Who was the first President of the United States?', 'mcq', '{"Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"}', 1, null),
('HISTORY', 'Which ancient wonder of the world still stands today?', 'mcq', '{"Colossus of Rhodes", "Hanging Gardens", "Great Pyramid of Giza", "Lighthouse of Alexandria"}', 2, null),
('HISTORY', 'In which year did Christopher Columbus reach the Americas?', 'mcq', '{"1490", "1491", "1492", "1493"}', 2, null),
('HISTORY', 'Who wrote the Declaration of Independence?', 'mcq', '{"George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"}', 1, null),
('HISTORY', 'Which empire was known as "the empire on which the sun never sets"?', 'mcq', '{"Roman Empire", "British Empire", "Ottoman Empire", "Mongol Empire"}', 1, null),
('HISTORY', 'In which year did the Titanic sink?', 'mcq', '{"1910", "1911", "1912", "1913"}', 2, null),
('HISTORY', 'Who was known as the "Iron Lady"?', 'mcq', '{"Queen Elizabeth II", "Margaret Thatcher", "Angela Merkel", "Indira Gandhi"}', 1, null),
('HISTORY', 'Which war was fought between the North and South in America?', 'mcq', '{"Revolutionary War", "Civil War", "World War I", "World War II"}', 1, null),
('HISTORY', 'In which year did the Berlin Wall fall?', 'mcq', '{"1987", "1988", "1989", "1990"}', 2, null),
('HISTORY', 'Who discovered penicillin?', 'mcq', '{"Marie Curie", "Alexander Fleming", "Louis Pasteur", "Robert Koch"}', 1, null),
('HISTORY', 'Which ancient civilization built Machu Picchu?', 'mcq', '{"Maya", "Aztec", "Inca", "Olmec"}', 2, null),
('HISTORY', 'In which year did the French Revolution begin?', 'mcq', '{"1787", "1788", "1789", "1790"}', 2, null),
('HISTORY', 'Who was the first person to walk on the moon?', 'mcq', '{"Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"}', 1, null),
('HISTORY', 'Which dynasty built the Great Wall of China?', 'mcq', '{"Han Dynasty", "Tang Dynasty", "Ming Dynasty", "Qing Dynasty"}', 2, null),
('HISTORY', 'In which year did World War I begin?', 'mcq', '{"1912", "1913", "1914", "1915"}', 2, null),
('HISTORY', 'Who painted the Mona Lisa?', 'mcq', '{"Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"}', 1, null),
('HISTORY', 'Which empire was ruled by Julius Caesar?', 'mcq', '{"Greek Empire", "Roman Empire", "Egyptian Empire", "Persian Empire"}', 1, null),
('HISTORY', 'In which year did the American Civil War end?', 'mcq', '{"1863", "1864", "1865", "1866"}', 2, null),
('HISTORY', 'Who was the last pharaoh of Egypt?', 'mcq', '{"Tutankhamun", "Cleopatra", "Nefertiti", "Hatshepsut"}', 1, null);
